### PR TITLE
Merge barry0 into main

### PR DESCRIPTION
**Pull request by barryb5**
Changes with generateScoutersSchedule to use matchKeys and include non-qual matches, addTestData is waiting on more sample data.

### CODE REVIEW

**Comment by barryb5** [comment]
Whoever owns HighlanderRobotics, could you add me as a contributor to this project, would appreciate being able to preview and approve pull requests for my server.

**Comment by Awesomeplayer165** [comment]
I think the problem is that someone [protected](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) the main branch

**Comment by Awesomeplayer165** [comment]
I remember seeing that suggestion when setting up my repo, and I think GitHub *recently* released this feature to free accounts with a public repo

**Comment by Awesomeplayer165** [comment]
Might want to tell tweak the changes of the protection.

**Comment by barryb5** [comment]
Yes also remove branch protection please, it should be somewhere under settings

**Pull request merged**
